### ISSUE TITLE
执行bash -c "$(curl -fsSL https://git.io/vuMdM)"出错

### ISSUE THREAD

**Issue by tttony3** [4679/oh-my-termux#1]
v: can't rename 'oh-my-termux/.termux': No such file or directory                                Hit:1 http://mirrors.tuna.tsinghua.edu.cn/termux stable InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
bash: line 19: git: command not found
cp: can't stat '/data/data/com.termux/files/home/.oh-my-zsh/templates/zshrc.zsh-template': No such file or directory
/data/data/com.termux/files/usr/bin/zsh is not an executable file!
Done!
怎么解决？

**Comment by 4679** [comment]
没装上git? 手动安装试试

**Comment by tttony3** [comment]
很忧愁啊
apt install git 
显示unable to locate package git 。。找不到

**Comment by 4679** [comment]
先apt update

**Comment by tttony3** [comment]
不知为何会出错 
apt list 里面有git 
update显示完成没有 0  can be upgraded 
酷安下的 卸了 
从google下就可以了
