### ISSUE TITLE
Hey I have a problem in your tool

### ISSUE THREAD

**Issue by vidhuran-cyber** [4679/oh-my-termux#10]
Hey I have a problem in your tool.
I will setup a background colour in my termux with your tool . But sometimes I need to remove the background colour . So tell me how to remove the background colour of your tool.

**Comment by 4679** [comment]
```bash
rm ~/.termux/colors.properties
```

**Comment by vidhuran-cyber** [comment]
Hey too many thanks for you I am programmer some times I use nano for programing
But the background is not suite for programing
But other uses I am surely use your background colours it is so nice
