### ISSUE TITLE
Hey sorry how to remove fonts style

### ISSUE THREAD

**Issue by vidhuran-cyber** [4679/oh-my-termux#11]
Hey sorry how to remove fonts style.
![Screenshot_2020-09-07-17-30-40-101_com termux](https://user-images.githubusercontent.com/66547158/92385939-701e9c80-f130-11ea-8000-d7d5f87ad52c.jpg)

**Comment by 4679** [comment]
```bash
rm ~/.termux/font.ttf
```

**Comment by vidhuran-cyber** [comment]
Hey very thanks for giving reply for me ☺️

**Comment by 4679** [comment]
you're welcome
