### ISSUE TITLE
Hey how can remove this .

### ISSUE THREAD

**Issue by vidhuran-cyber** [4679/oh-my-termux#12]
Hey how can remove this .
![IMG_20200907_174300](https://user-images.githubusercontent.com/66547158/92386558-a27cc980-f131-11ea-929b-cbf4ab2af18b.jpg)

**Comment by 4679** [comment]
```bash
rm -rf ~/.zshrc ~/.oh-my-zsh
chsh -s bash
pkg uninstall -y zsh
```
