### ISSUE TITLE
Install mangles sources.list on x86 devices

### ISSUE THREAD

**Issue by asmfreak** [4679/oh-my-termux#2]
The mirror provided in sources.list is incorrect for x86 devices. This causes faulty installation if git or zsh packages were not installed earlier.

**Comment by jemyzhang** [comment]
@4679 you should first check the arch type before modify the source.list.

**Comment by 4679** [comment]
yep,I'll fix that.

**Comment by 4679** [comment]
https://github.com/4679/oh-my-termux/commit/ba892d2a8020f05cb66c97a1f56bb84817291ca1
