### ISSUE TITLE
Background colour

### ISSUE THREAD

**Issue by Auxilus** [4679/oh-my-termux#5]
How do I change the background colour to something like this...
https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQAqSDp6dkL02rf7ea6-vs-GdGaUvR3SiYvSYxiMUniHueWoVBsO9yE8IeeYQ

**Comment by Auxilus** [comment]
This is awesome though

**Comment by 4679** [comment]
Edit ~/.termux/colors.properties

**Comment by Auxilus** [comment]
Thanks!!!
Awesome themes

**Comment by 4679** [comment]
Glad to hear that
