### ISSUE TITLE
curl: (48) An unknown option was passed in to libcurl

### ISSUE THREAD

**Issue by 0x008800** [4679/oh-my-termux#7]
i installed "curl" but when i try `bash -c "$(curl -fsSL https://git.io/oh-my-termux)"` it get below output  https://imgur.com/a/NfzeZg1

**Comment by 4679** [comment]
can't replicate

![Screenshot_Termux_20190306-112529.png](https://i.loli.net/2019/03/06/5c7f3f0085ba4.png)

**Comment by Vista1nik** [comment]
Install fresh termux to replicate.
I have same problem.

**Comment by Vista1nik** [comment]
Run `apt upgrade` to update libcurl.
